### ISSUE TITLE
Cant get it to work 

### ISSUE THREAD

**Issue by negrofei** [icjmaa/MySFTP#8]
Hi. 
_Hola_

I could create a new server configuration file like this
_Pude crear el archivo de configuración siguiente:_
[
	{
		"remote_path": "/home/martin.feijoo/", 
		"port": "22", 
		"type": "sftp", 
		"password": "mypassword", 
		"user": "martin.feijoo", 
		"host": "nimbus.cima.fcen.uba.ar", 
		"nick": "yo"
	}
]

But after that I don't know how to make it work. Where do I have to press Enter?
When I click Listar servidor it shows only the option of "Nuevo servidor" 
_Pero después de eso no lo pude hacer andar. En ningun momento obtengo ningun mensaje de que haya funcionado._ 
_Cuando hago click en Listar servidores no me aparece el que yo configuré, únicamente Nuevo servidor._

Should I run the MySFTP.py file? 
_Debería correr el MySFTP.py?_

**Comment by negrofei** [comment]
Somehow, I do not know what happened, in Console this error shows:

Traceback (most recent call last):
  File "/home/martin/Desktop/sublime_text_3/sublime_plugin.py", line 949, in is_visible_
    ret = self.is_visible(**args)
TypeError: is_visible() got an unexpected keyword argument 'command'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/martin/Desktop/sublime_text_3/sublime_plugin.py", line 953, in is_visible_
    ret = self.is_visible()
  File "/home/martin/.config/sublime-text-3/Packages/MySFTP/MySFTP.py", line 138, in is_visible
    return False if os.path.dirname(self.window.active_view().file_name()) != Configuration.tmp_path else True
  File "./python3.3/posixpath.py", line 151, in dirname
AttributeError: 'NoneType' object has no attribute 'rfind'

**Comment by icjmaa** [comment]
@negrofei 
save the file of configuration into directory "C:\Users\[USER]\AppData\Roaming\Sublime Text 3\Packages\User\MySFTP\servers" if your SO is windows or "/home/[USER]/.config/sublime-text-3/Packages/User/MySFTP/servers" if is Linux, with extension ".json" for example "myserver.json"

**Comment by negrofei** [comment]
Thank you very much! Now I could connect
